name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      -*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: monitor        

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"  
        
    outputs:
        tag: ${{ steps.latest-tag.outputs.tag }}
  
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    needs: [get-latest-tag]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag gane5h/monitor:${{ needs.get-latest-tag.outputs.tag}}
        
      - name: Log into registry
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSSWORD}}
        run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login docker.io -u gane5h --password-stdin 

      - name: Push image
        run: |
          docker push gane5h/monitor:${{ needs.get-latest-tag.outputs.tag}}
